api_version: core/v2
type: Asset
metadata:
  namespace: demo
  name: prometheus-collector
spec:
  url: https://github.com/sensu/sensu-prometheus-collector/releases/download/1.1.4/sensu-prometheus-collector_1.1.4_linux_amd64.tar.gz
  sha512: 8d2a5ea6d97818f0da97e8bcf1f2ca765d7acb890dba0682dd35cc6f09714da59b7e974d7f8dbaba507fefa2104b3e145bd31f924fdf154b8870892d0afb4767
