api_version: core/v2
type: CheckConfig
metadata:
  namespace: demo
  name: dummy-app-prometheus
spec:
  runtime_assets:
  - prometheus-collector
  command: sensu-prometheus-collector -exporter-url http://localhost:8080/metrics
  subscriptions:
  - dummy
  publish: true
  interval: 10
  output_metric_format: influxdb_line
  output_metric_handlers:
  - influxdb
