api_version: core/v2
type: CheckConfig
metadata:
  namespace: demo
  name: kube-state-prometheus
spec:
  runtime_assets:
  - prometheus-collector
  command: sensu-prometheus-collector -exporter-url http://kube-state-metrics.kube-system.svc.cluster.local:8080/metrics
  subscriptions:
  - roundrobin:daemonset
  publish: true
  interval: 10
  output_metric_format: influxdb_line
  output_metric_handlers:
  - influxdb
