api_version: core/v2
type: CheckConfig
metadata:
  namespace: demo
  name: cadvisor-metrics
spec:
  runtime_assets:
  - prometheus-collector
  command: sensu-prometheus-collector -exporter-url http://$HOST_IP:10255/metrics
  subscriptions:
  - daemonset
  publish: true
  interval: 30
  output_metric_format: influxdb_line
  output_metric_handlers:
  - influxdb
